### ISSUE TITLE
guestbook | Never_yu's Blog

### ISSUE THREAD

**Issue by Neveryu** [Neveryu/Neveryu.github.io#6]
https://neveryu.github.io/guestbook/

**Comment by Neveryu** [comment]
:smile:
期待下一阶段的旅程

**Comment by zhaoxmf** [comment]
这个评论功能还挺好用的

**Comment by xbher** [comment]
大佬我的local search 一直没用怎么解决？

**Comment by xbher** [comment]
建议写一篇关于hexo博客备份的文章

**Comment by zhangyu0806** [comment]
鼠标点击的心和移动的线段是怎么实现的呢？

**Comment by Neveryu** [comment]
@zhangyu0806 
不知道你有没有看这篇文章 [Hexo-NexT搭建个人博客（二）](https://neveryu.github.io/2016/09/30/hexo-next-two/#5-%E9%BC%A0%E6%A0%87%E7%82%B9%E5%87%BB%E5%B0%8F%E7%BA%A2%E5%BF%83%E7%9A%84%E8%AE%BE%E7%BD%AE) 第5和第6条有介绍到，看看能不能实现。

**Comment by zhangyu0806** [comment]
Thanks，已设置好。

发送自 Windows 10 版邮件应用

发件人: Yu
发送时间: 2017年10月9日 9:57
收件人: Neveryu/Neveryu.github.io
抄送: zhangyu; Mention
主题: Re: [Neveryu/Neveryu.github.io] guestbook | Never_yu's Blog (#6)

@zhangyu0806
不知道你有没有看这篇文章 Hexo-NexT搭建个人博客（二） 第5和第6条有介绍到，看看能不能实现。

**Comment by anson2416** [comment]
想问下最后你的“博客源码 ， 欢迎 star”，“作者：Neveryu”的效果怎样生成出来的？

**Comment by Neveryu** [comment]
@anson2416 
文章中是这样写的：
```
<h5 style="color:#f63;"><i>最后要说的是：</i></h5>
<p id="div-border-top-green"><i>[博客源码](https://github.com/Neveryu/Neveryu.github.io) ， 欢迎 star
</i></p>
```
然后，你的css样式中要有`#div-border-top-green`的样式。
我的样式表这这里：[https://github.com/Neveryu/Neveryu.github.io/blob/resource/themes/next/source/css/_custom/custom.styl](https://github.com/Neveryu/Neveryu.github.io/blob/resource/themes/next/source/css/_custom/custom.styl)

**Comment by sttomato** [comment]
博主您好，我想问一下，这个“Click to Expand”是怎么实现的？

**Comment by dp9x** [comment]
挺不错的

**Comment by gavin971** [comment]
不错，点个赞！

**Comment by evilpwn** [comment]
博主您好，请问你的404怎么写的？为什么我写出来的404，还是有sidebar，里面还有“文章目录  站点概览”。。。。。。

**Comment by SunDuncan** [comment]
博主你有遇到这种问题嘛？在我本地的localhost 运行ok,但传到github,上运行无效，比如你那个high起来。本地可以，但线上不行。求教

**Comment by SunDuncan** [comment]
多说现在好像访问不了了

**Comment by Neveryu** [comment]
@SunDuncan 你那个 high 运行无效，是因为你的音乐链接的原因，我直接拿网易云的音乐链接，也不行

**Comment by Neveryu** [comment]
@evilpwn 这个.....可能要看一下你 sidebar 的配置

**Comment by WTGrim** [comment]
hexo new "文章标题"   然后hexo g   hexo  d  为什么创建的文章不显示呢

**Comment by dp9x** [comment]
你可以试一试hexo cl |hexo g |hexo d

Sent from my Windows 10 phone

________________________________

**Comment by Vincentqyw** [comment]
博主你好，我使用的是Hexo Next 主题的Gemini scheme。[我的博客](www.vincentqin.tech)的字体在本机上显示是正常的，但是换了一台机器之后查看博客字体就不对了。字体配置如下：

``` yml
font:
  enable: true

  # Uri of fonts host. E.g. //fonts.googleapis.com (Default).
  host: 

  # Font options:
  # `external: true` will load this font family from `host` above.
  # `family: Times New Roman`. Without any quotes.
  # `size: xx`. Use `px` as unit.

  # Global font settings used on <body> element.
  global:
    external: true
    family: Monda
    size:  

  # Font settings for Headlines (h1, h2, h3, h4, h5, h6).
  # Fallback to `global` font settings.
  headings:
    external: true
    family: Roboto Slab
    size:

  # Font settings for posts.
  # Fallback to `global` font settings.
  posts:
    external: true
    family: Garamond

  # Font settings for Logo.
  # Fallback to `global` font settings.
  logo:
    external: true
    family: Lobster Two
    size: 24

  # Font settings for <code> and code blocks.
  codes:
    external: true
    family: true
    size: PT Mono
```
请问博主这个问题如何解决？
